# Generated by Django 5.2.17 on 2026-08-28 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('VNPAY', 'VNPay')], default='VNPAY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('txn_ref', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('payment_url', models.TextField(blank=True)),
                ('provider_transaction_no', models.CharField(blank=True, max_length=50)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=20)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='billing_pay_subscri_144c63_idx'), models.Index(fields=['status', 'expires_at'], name='billing_pay_status_000f68_idx')],
            },
        ),
    ]
