# Generated by Django 5.2.17 on 2026-08-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ingestion_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='vector_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
