"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-development-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost"],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'accounts',
    'billing',
    'documents',
    'chat',
    'usage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=[
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ],
)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL'),
}
DATABASES['default']['CONN_MAX_AGE'] = 60
DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

REDIS_URL = env('REDIS_URL', default='redis://127.0.0.1:6379/0')

OPENROUTER_API_KEY = env('OPENROUTER_API_KEY', default='')
OPENROUTER_BASE_URL = env(
    'OPENROUTER_BASE_URL',
    default='https://openrouter.ai/api/v1',
)
OPENROUTER_EMBEDDING_MODEL = env(
    'OPENROUTER_EMBEDDING_MODEL',
    default='openai/text-embedding-3-small',
)
OPENROUTER_EMBEDDING_DIMENSIONS = env.int(
    'OPENROUTER_EMBEDDING_DIMENSIONS',
    default=1536,
)
OPENROUTER_SITE_URL = env('OPENROUTER_SITE_URL', default='http://127.0.0.1:8000')
OPENROUTER_APP_NAME = env('OPENROUTER_APP_NAME', default='RAVID Private Knowledge API')
OPENROUTER_CHAT_MODEL = env('OPENROUTER_CHAT_MODEL', default='openrouter/free')
OPENROUTER_HYDE_MODEL = env('OPENROUTER_HYDE_MODEL', default=OPENROUTER_CHAT_MODEL)
LANGCHAIN_PG_CONNECTION = env(
    'LANGCHAIN_PG_CONNECTION',
    default=env('DATABASE_URL'),
)
if LANGCHAIN_PG_CONNECTION.startswith('postgresql://'):
    LANGCHAIN_PG_CONNECTION = LANGCHAIN_PG_CONNECTION.replace(
        'postgresql://',
        'postgresql+psycopg://',
        1,
    )
RAG_CHUNK_SIZE = env.int('RAG_CHUNK_SIZE', default=1000)
RAG_CHUNK_OVERLAP = env.int('RAG_CHUNK_OVERLAP', default=200)
RAG_RETRIEVAL_K = env.int('RAG_RETRIEVAL_K', default=5)
RAG_MAX_OUTPUT_TOKENS = env.int('RAG_MAX_OUTPUT_TOKENS', default=1000)
HYDE_MAX_OUTPUT_TOKENS = env.int('HYDE_MAX_OUTPUT_TOKENS', default=400)
HYDE_TIMEOUT_SECONDS = env.float('HYDE_TIMEOUT_SECONDS', default=20.0)

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

VNPAY_TMN_CODE = env(
    'VNP_TMNCODE',
    default=env('VNPAY_TMN_CODE', default=''),
)
VNPAY_HASH_SECRET = env(
    'VNP_HASHSECRET',
    default=env('VNPAY_HASH_SECRET', default=''),
)
VNPAY_URL = env(
    'VNPAY_URL',
    default='https://sandbox.vnpayment.vn/paymentv2/vpcpay.html',
)
VNPAY_RETURN_URL = env(
    'VNPAY_RETURN_URL',
    default='http://127.0.0.1:8000/api/payments/vnpay/return/',
)
VNPAY_IPN_URL = env(
    'VNPAY_IPN_URL',
    default='http://127.0.0.1:8000/api/payments/vnpay/ipn/',
)
VNPAY_VERSION = env('VNPAY_VERSION', default='2.1.0')
VNPAY_COMMAND = env('VNPAY_COMMAND', default='pay')
VNPAY_ORDER_TYPE = env('VNPAY_ORDER_TYPE', default='other')
VNPAY_LOCALE = env('VNPAY_LOCALE', default='vn')
VNPAY_PAYMENT_TTL = timedelta(minutes=15)
VNPAY_PROCESS_RETURN = env.bool('VNPAY_PROCESS_RETURN', default=DEBUG)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'RAVID Private Knowledge API',
    'DESCRIPTION': 'Private document ingestion, billing, and RAG chat APIs.',
    'VERSION': '1.0.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    # FileField is binary in requests but a URL in responses. Splitting request
    # components makes Swagger render a real file picker for multipart uploads.
    'COMPONENT_SPLIT_REQUEST': True,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
